# Generated by Django 3.0.4 on 2020-03-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('mcode', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('mname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('pid', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('pname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=5)),
                ('rm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cw.Module')),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cw.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2020)),
                ('semester', models.IntegerField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cw.Module')),
                ('professor', models.ManyToManyField(to='cw.Professor')),
            ],
        ),
    ]
